### ISSUE TITLE
Column disappeared after reset and a new column

### ISSUE THREAD

**Issue by saddleupandride** [Redon-Tech/Emergency-Vehicle-Creator#13]
![image](https://github.com/Redon-Tech/Emergency-Vehicle-Creator/assets/102647280/874ca387-4096-4b2d-9617-42ad987d4a9f)

Nothing seen in output, similar to [Issue 11](https://github.com/Redon-Tech/Emergency-Vehicle-Creator/issues/11)

After attempting to generate new row, it does generate 1 new row in all columns. If attempting to delete row when column empty, a translucent grey overlay is shown nothing in output, though the rest of the UI still functions.
![image](https://github.com/Redon-Tech/Emergency-Vehicle-Creator/assets/102647280/26517a03-1492-4686-bb22-2d229f5d2a6d)

**Comment by saddleupandride** [comment]
![image](https://github.com/Redon-Tech/Emergency-Vehicle-Creator/assets/102647280/160b4468-8a43-4704-97d4-367c805ac8e3)
Regarding generating rows

**Comment by saddleupandride** [comment]
Appears to be a sporadic thing, sometimes it generates a full column (minus 2 from the usual amount), or 2 rows, or 0 rows...

**Comment by parker02311** [comment]
Fixed in 008c6634af7954672dd2059e7e54ed8089d9959c

**Comment by saddleupandride** [comment]
Still appears to be happening sporadically, just happened earlier tonight

**Comment by parker02311** [comment]
@saddleupandride do you have any videos of it happening now. Also is it happening in a way that can be reproduced?

**Comment by parker02311** [comment]
I still need additional output screenshots and videos of the issue happening again or a way to reproduce the issue in order to fix this bug.

**Comment by parker02311** [comment]
Closing as stale
